# Generated by Django 4.2.9 on 2024-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('pro_des', models.CharField(default='', max_length=250)),
                ('pro_price', models.IntegerField(default=0)),
                ('pro_img', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
