# Generated by Django 5.0 on 2024-01-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='store.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_img',
            field=models.ImageField(upload_to='uploaded/products/'),
        ),
    ]
