# Generated by Django 4.2.9 on 2024-01-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
